package study.leetcode.section350.no389;

import java.util.HashMap;
import java.util.Map;
import java.util.Set;

/**
 * <h2>Find the Difference</h2>
 * Given two strings <b>s</b> and <b>t</b> which consist of only lowercase letters.
 * <p>
 * String <b>t</b> is generated by random shuffling string <b>s</b> and then add one more letter at a random position.
 * <p>
 * Find the letter that was added in <b>t</b>.
 * <p>
 * <b>Example:</b>
 * <pre><code>
 * Input:
 * s = "abcd"
 * t = "abcde"
 *
 * Output:
 * e
 *
 * Explanation:
 * 'e' is the letter that was added.
 * </code></pre>
 *
 * @see <a href="https://leetcode-cn.com/problems/find-the-difference/">
 * Find the Difference</a>
 */
public class Solution389 {
    public char findTheDifference(String s, String t) {
        char[] sArray = s.toCharArray();
        char[] tArray = t.toCharArray();

        HashMap<String, Integer> sMap = new HashMap<>();
        for (char a : sArray) {
            String key = String.valueOf(a);
            if (sMap.get(key) == null) {
                sMap.put(String.valueOf(a), 1);
            } else {
                int count = sMap.get(key);
                sMap.put(key, count + 1);
            }
        }

        char result = 0;
        for (char b : tArray) {
            String key = String.valueOf(b);
            if (sMap.get(key) != null) {
                int count = sMap.get(key);
                sMap.put(key, count - 1);
            } else {
                sMap.put(key, -1);
            }
        }

        Set<Map.Entry<String, Integer>> set = sMap.entrySet();
        for (Map.Entry<String, Integer> entry : set) {
            if (entry.getValue() != null && entry.getValue() == -1) {
                result = entry.getKey().charAt(0);
            }
        }
        return result;

    }
}
